# For more information: https://laravel.com/docs/sail
version: "2.4"
services:
  laravel:
    build:
      context: ./docker/8.0
      dockerfile: Dockerfile
      args:
        WWWGROUP: "${WWWGROUP}"
    image: sail-8.0/app
    ports:
      - "${APP_PORT:-80}:80"
    environment:
      WWWUSER: "${WWWUSER}"
      LARAVEL_SAIL: 1
    volumes:
      - vscode-ext:/home/sail/.vscode-server/extensions
      - vscode-ext-insiders:/home/sail/.vscode-server-insiders/extensions
      - vendor:/var/www/html/vendor
      - node-modules:/var/www/html/node_modules
      - ".:/var/www/html"
    networks:
      - sail
    depends_on:
      - mysql
      - redis
      - selenium
  mysql:
    image: "mysql:5.7.29"
    ports:
      - "${FORWARD_DB_PORT:-3306}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - "sailmysql:/var/lib/mysql"
    networks:
      - sail
    healthcheck:
      test: ["CMD", "mysqladmin", "ping"]
  redis:
    image: "redis:alpine"
    ports:
      - "${FORWARD_REDIS_PORT:-6379}:6379"
    volumes:
      - "sailredis:/data"
    networks:
      - sail
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
  meilisearch:
    image: "getmeili/meilisearch:latest"
    ports:
      - "${FORWARD_MEILISEARCH_PORT:-7700}:7700"
    volumes:
      - "sailmeilisearch:/data.ms"
    networks:
      - sail
  mailhog:
    image: "mailhog/mailhog:latest"
    ports:
      - "${FORWARD_MAILHOG_PORT:-1025}:1025"
      - "${FORWARD_MAILHOG_DASHBOARD_PORT:-8025}:8025"
    networks:
      - sail
  selenium:
    image: "selenium/standalone-chrome"
    volumes:
      - "/dev/shm:/dev/shm"
    networks:
      - sail
networks:
  sail:
    driver: bridge
volumes:
  vendor:
    driver: local
  node-modules:
    driver: local
  vscode-ext:
    driver: local
  vscode-ext-insiders:
    driver: local
  sailmysql:
    driver: local
  sailredis:
    driver: local
  sailmeilisearch:
    driver: local
